In this chapter, we will be looking at a real dataset which can be found on Kaggle. The dataset we’ll be using is the Pima Indians Diabetes datase.

We’re going to import the csv file using Pandas. Pandas is a famous data science library used to hold data and analyze data. It holds the data in what is known as a dataframe.

Source: https://medium.com/a-coders-guide-to-ai/a-coders-guide-to-neural-networks-chapter-4-pima-indians-diabetes-dataset-431c90be767f

In [ ]:
import pandas as pd
import torch
import matplotlib.pyplot as plt

Let's import the dataset

In [ ]:
df = pd.read_csv(r'https://raw.githubusercontent.com/a-coders-guide-to-ai/a-coders-guide-to-neural-networks/master/data/diabetes.csv')

In [ ]:
df.head() # Let's take a look at how the data looks like

Similar to previous chapters, we have 1 neuron and our loss function will remain the BCE. The only difference is, instead of 2 inputs (i.e. X and 1), we now have 9 inputs (i.e. all the features of the dataset and 1).

Let's predict with Logistic Regression. We will split our dataset into 2 parts. 1 part holding the features and the other holding the target. Thereafter, we’ll turn those into tensors.

In [ ]:
X = df[df.columns[:-1]] # takes all the columns of the dataset, except for the last column
y = df['Outcome'] #  only takes the Outcome column and assigns it to y

X = torch.tensor(X.values)
y = torch.tensor(y.values)

X = torch.cat((X, torch.ones(X.shape[0], dtype=float).reshape(-1,1)), dim=1)

Let's start writing the regression code now taking motivation from the previous chapter


In [ ]:
def log_loss(y, y_pred): ##log loss error (binary cross entropy)
  return -torch.sum((y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)))/y.shape[0]

def sigmoid(linear):
    return 1/(1+torch.exp(-linear))

epoch_loss = []

weights = torch.zeros(9, dtype=float, requires_grad=True)
learning_rate = 1e-4
n = X.shape[0]

for epoch in range(8000+1): 
    linear = weights.reshape(1,-1)@X.T ##one equation for all
    print(weights.reshape(1,-1))
    print(weights)

    y_pred =  sigmoid(linear) ##logistic
    loss = log_loss(y, y_pred)
    epoch_loss.append(loss.item())

    ###backpropagation###
    loss.backward()

    ###step###
    with torch.no_grad():
        weights -= learning_rate * weights.grad

    weights.grad.zero_()

    if(epoch % 1000 == 0):
        acc = torch.sum(((y_pred>=0.5)+0 == y)+0).item()/y.shape[0]
        print('epoch: {0} - loss: {1:.5f}; acc: {2:.3f}'.format(epoch, epoch_loss[-1], acc))

In [ ]:
# Sample to check how reshape works
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.reshape(a, (1,-1)))

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
